package com.automobile.experience.main.model.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "customer_login")
public class UserLogin {
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String customerId;	
	
	@DynamoDBAttribute
	private String password;
	
	@DynamoDBAttribute
	private String username;
	
	public UserLogin() {
		super();
	}
	
	public UserLogin(String customerId, String password, String username) {
		super();
		this.customerId = customerId;
		this.password = password;
		this.username = username;
	}
	
	public UserLogin(String customerId) {
		this.customerId = customerId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Override
	public String toString() {
		return super.toString();
	}
}
