package com.automobile.experience.main.model.entities;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Document(collection="user_login")
public class UserLogin {
	
	@Id
	private int customerId;	
	
	private String password;
	
	private String username;
	
	public UserLogin() {
		super();
	}
	
	public UserLogin(int customerId, String password, String username) {
		super();
		this.customerId = customerId;
		this.password = password;
		this.username = username;
	}
	
	public UserLogin(int customerId) {
		this.customerId = customerId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getCustomerId() {
		return customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Override
	public String toString() {
		return "User [customerId=" + customerId + ", username=" + username + ", password=" + password + "]";
	}
}
